apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-csi-controller
  namespace: kubevirt-csi-driver
spec:
  template:
    spec:
      volumes:
        - name: tenantcluster
          secret:
            secretName: capi-quickstart-kubeconfig
