namespace: default
resources:
- infra-cluster-service-account.yaml
- infra-namespace-configmap.yaml
- ../base
#- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.62.0/cdi-operator.yaml
#- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.62.0/cdi-cr.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: controller.yaml
